// Auto-generated by scripts/build-influence-weights.js — do not edit by hand.
// Run `node scripts/build-influence-weights.js` to populate.
export const INFLUENCE_WEIGHTS: Record<string, Record<string, number>> = {};

/** Highest weight for the pair (slugA, slugB) in either direction; 1.0 if unknown. */
export function getInfluenceWeight(slugA: string, slugB: string): number {
  return INFLUENCE_WEIGHTS[slugA]?.[slugB]
    ?? INFLUENCE_WEIGHTS[slugB]?.[slugA]
    ?? 1.0;
}
